sonata_user:
    admin:                  # Admin Classes
        user:
            class:          Application\Sonata\UserBundle\Admin\UserAdmin
            controller:     ApplicationSonataUserBundle:UserAdmin